stages:
  - build
  - deploy

build_pages:
  stage: build
  image: python:latest
  script:
  - pip install -U sphinx sphinx-rtd-theme sphinx-prompt
  - sphinx-build -W -n -b html doc/source public
  artifacts:
    paths:
    - public
  only:
  - branches
  except:
  - master

pages:
  stage: deploy
  image: python:latest
  script:
  - pip install -U sphinx sphinx-rtd-theme sphinx-prompt
  - sphinx-build -b html doc/source public
  artifacts:
    paths:
    - public
  only:
  - master

kicad:
  stage: deploy
  image: kicad/kicad:7.0
  script:
  - mkdir --parents hardware_docs
  - kicad-cli sch export pdf Copilot_Lite/Hardware/Copilot_Lite.kicad_sch --output hardware_docs/Copilot_Lite.pdf
  artifacts:
    expose_as: 'hardware documents'
    paths: ['hardware_docs']
  only:
  - master
